version: '3'
services:

  cdp-screenshot:
    image: cdp-screenshot:v1.0.0
    ports:
      - "8888:8888"
    environment:
      WsURL: "ws://chromedp:9222/"
    depends_on:
      - chromedp

  chromedp:
    image: chromedp/headless-shell:107.0.5304.107_CN
    init: true # 解决僵尸进程问题
    shm_size: '2gb'
    command: ["--font-render-hinting=none", "--window-size=1920,1080", "--incognito=true", "--ignore-certificate-errors=true", "--disable-web-security=true", "--no-first-run=true", "--no-default-browser-check=true", "--disable-extensions=true", "--disable-default-apps=true"]
    ports:
      - "9222:9222"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 4096M