// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	URL            string `json:"url"`
	Clarity        int    `json:"clarity,optional,range=[1:10]"`
	Quality        int    `json:"quality,optional,range=[1:100]"`
	ViewportWidth  int    `json:"viewportWidth,optional"`
	ViewportHeight int    `json:"viewportHeight,optional"`
	Timeout        int    `json:"timeout,optional"`
}
